# Generated by Django 2.1.7 on 2020-06-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMunicipio', models.CharField(max_length=20)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProTransApp.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_transporte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTransporte', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('domicilio', models.CharField(max_length=50)),
            ],
        ),
    ]
