# Generated by Django 2.1.7 on 2020-07-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombreDepartamento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idrespuesta', models.AutoField(primary_key=True, serialize=False)),
                ('numerodepregunta', models.IntegerField()),
            ],
            options={
                'db_table': 'respuesta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo_transporte',
            fields=[
                ('tipo_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipoTransporte', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dui', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('edad', models.PositiveSmallIntegerField()),
                ('domicilio', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('idreclamo', models.ForeignKey(db_column='dui', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ProTransApp.Usuario')),
                ('realizado', models.BooleanField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reclamo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(db_column='departamento', on_delete=django.db.models.deletion.DO_NOTHING, to='ProTransApp.Departamento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tipo_transporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ProTransApp.Tipo_transporte'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='dui',
            field=models.ForeignKey(db_column='dui', on_delete=django.db.models.deletion.DO_NOTHING, to='ProTransApp.Usuario'),
        ),
    ]
