# Generated by Django 2.1.7 on 2020-06-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProTransApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
